[package]
name = "aoc-2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
regex = "1"
bimap = "0.6.1"
priority-queue = "1.2.1"
